# Generated by Django 3.0.4 on 2020-03-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, null=True)),
                ('no_hp', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, null=True)),
                ('harga', models.FloatField(null=True)),
                ('kategori', models.CharField(choices=[('Olahraga', 'Olahraga'), ('Edukasi', 'Edukasi'), ('Hiburan', 'Hiburan')], max_length=20, null=True)),
                ('deskripsi', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Tertunda', 'Tertunda'), ('Terkirim', 'Terkirim'), ('Dalam Perjalan', 'Dalam Perjalan')], max_length=20, null=True)),
                ('pelanggan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Pelanggan')),
                ('produk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Produk')),
            ],
        ),
    ]
